apiVersion: apps/v1
kind: Deployment
metadata:
  name: centos7-base
  namespace: centos7-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos7-base
  template:
    metadata:
      labels:
        app: centos7-base
    spec:
      containers:
      - name: centos7-base
        image: minoent.azurecr.io/centos/centos:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
